load("@bazel-go-mod-experiment//rules:go_mod.bzl", "go_mod")
load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_mod",
    srcs = ["extension.go"],
    importpath = "bazel-go-mod-experiment/tools/gazelle_go_mod/tools/gazelle_go_mod",
    visibility = ["//visibility:public"],
    deps = [
        "@gazelle//language",
        "@gazelle//resolve",
        "@gazelle//rule",
    ],
)

go_mod(
    name = "go_mod_zip",
    go_mod = ":go.mod",
    module_path = "extensions/gazelle/go_mod",
    deps = [":go_mod"],
)

go_test(
    name = "go_mod_test",
    srcs = ["extension_test.go"],
    embed = [":go_mod"],
    deps = [
        "@gazelle//language",
        "@gazelle//rule",
    ],
)

filegroup(
    name = "_pkg_",
    srcs = [
        "BUILD.bazel",
        "extension.go",
        "extension_test.go",
        "go.mod",
        "go.sum",
    ],
    visibility = ["//:__subpackages__"],
)
